services:
  broker:
    image: eclipse-mosquitto
    container_name: broker
    privileged: true
    volumes:
      - ./broker/mosquitto/config:/mosquitto/config
      - ./broker/mosquitto/data:/mosquitto/data
      - ./broker/mosquitto/log:/mosquitto/log
    network_mode: host
    restart: unless-stopped