services:
  broker:
    image: eclipse-mosquitto
    container_name: broker
    privileged: true
    ports:
      - "1883:1883"
    volumes:
      - ./broker/mosquitto/config:/mosquitto/config
      - ./broker/mosquitto/data:/mosquitto/data
      - ./broker/mosquitto/log:/mosquitto/log
    networks:
      IoTnet:

  client1:
    image: mqttclient
    container_name: client1
    command: bash -c "sleep infinity"
    privileged: true
    volumes:
      - ./clients/cl1:/home/
    networks:
      IoTnet:
        ipv4_address: 192.168.0.100 

  client2:
    image: mqttclient
    container_name: client2
    command: bash -c "sleep infinity"
    privileged: true
    volumes:
      - ./clients/cl1:/home/
    networks:
      IoTnet:
        ipv4_address: 192.168.0.101

  observador:
    image: kalitfg
    container_name: observador
    command: bash -c "sleep infinity"
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    volumes:
      - ./observador:/home/ #"xhost +local:" si no va
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      IoTnet:
        ipv4_address: 192.168.0.102

networks:
  IoTnet:
    driver: ipvlan
    driver_opts:
      parent: wlp42s0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          
